
services:
  snry:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/sonroyaalmerol/snry-dev-space:latest
    container_name: snry-dev-space
    hostname: snry
    init: true
    ports:
      - "2222:22"
    environment:
      - INSTALL_DEFAULTS=true
      - PI_CODING_AGENT_DIR=/home/snry/.pi/agent
      - TERM=xterm-256color
    volumes:
      - snry-home:/home/snry/.pi
      - ./workspace:/home/snry/workspace
    secrets:
      - snry-auth
      - snry-ssh-key
    stdin_open: true
    tty: true

volumes:
  snry-home:
    driver: local

secrets:
  snry-auth:
    file: ./secrets/auth.json
  snry-ssh-key:
    file: ./secrets/authorized_keys